# Model listesi
MODEL_LIST = [
'AdaBoost_7_Sosyal',
'LogisticRegression_7_Sosyal',
'LogisticRegression_6_Sosyal',
'AdaBoost_6_Sosyal',
'SVM_7_Sosyal',
'NeuralNetwork_7_Sosyal',
'KNN_6_Sosyal',
'RandomForest_7_Sosyal',
'DecisionTree_7_Sosyal',
'XGBoost_7_Sosyal',
'KNN_7_Sosyal',
'LogisticRegression_7_Duyusal',
'LogisticRegression_9_Duyusal',
'AdaBoost_9_Duyusal',
'AdaBoost_7_Duyusal',
'NeuralNetwork_7_Duyusal',
'SVM_7_Duyusal',
'AdaBoost_10_Duyusal',
'LogisticRegression_10_Duyusal',
'LogisticRegression_6_Duyusal',
'NeuralNetwork_9_Duyusal',
'KNN_7_Duyusal',
'NeuralNetwork_6_Duyusal',
'LightGBM_7_Duyusal',
'AdaBoost_6_Duyusal',
'XGBoost_6_Duyusal',
'NeuralNetwork_10_Motor',
'RandomForest_10_Motor',
'SVM_10_Motor',
'SVM_9_Motor',
'LightGBM_10_Motor',
'LogisticRegression_9_Motor',
'XGBoost_10_Motor',
'LogisticRegression_7_Motor',
'KNN_7_Motor',
'KNN_9_Motor',
'SVM_7_Motor',
'NeuralNetwork_9_Motor',
'NeuralNetwork_7_Motor',
'RandomForest_9_Motor',
'LightGBM_9_Motor',
'RandomForest_7_Motor',
'AdaBoost_5_Motor',
'LightGBM_5_Motor',
'AdaBoost_6_Motor',
'XGBoost_7_Motor',
'XGBoost_9_Motor',
'SVM_5_Motor',
'XGBoost_5_Motor',
'NeuralNetwork_5_Motor',
'LightGBM_7_Motor',
'LightGBM_8_Dil',
'AdaBoost_6_Dil',
'LogisticRegression_6_Dil',
'SVM_8_Dil',
'RandomForest_6_Dil',
'KNN_8_Dil',
'NeuralNetwork_8_Dil',
'DecisionTree_6_Dil',
'LogisticRegression_8_Dil',
'SVM_6_Dil',
'AdaBoost_8_Dil',
'LogisticRegression_9_Ortak_Dikkat',
'SVM_9_Ortak_Dikkat',
'LogisticRegression_10_Ortak_Dikkat',
'SVM_10_Ortak_Dikkat',
'KNN_9_Ortak_Dikkat',
'NeuralNetwork_10_Ortak_Dikkat',
'NeuralNetwork_9_Ortak_Dikkat',
'KNN_10_Ortak_Dikkat',
'AdaBoost_10_Ortak_Dikkat',
'RandomForest_9_Ortak_Dikkat',
'AdaBoost_9_Ortak_Dikkat',
'XGBoost_10_Ortak_Dikkat',
'XGBoost_9_Ortak_Dikkat',
'LogisticRegression_8_Ortak_Dikkat',
'KNN_8_Ortak_Dikkat',
'NeuralNetwork_8_Ortak_Dikkat',
'RandomForest_10_Ortak_Dikkat',
'LightGBM_10_Ortak_Dikkat',
'AdaBoost_8_Ortak_Dikkat',
'LightGBM_9_Ortak_Dikkat',
'SVM_8_Ortak_Dikkat',
'LightGBM_8_Ortak_Dikkat',
'XGBoost_8_Ortak_Dikkat',
'LogisticRegression_7_Ortak_Dikkat',
'NeuralNetwork_7_Ortak_Dikkat',
'LogisticRegression_7_Iletisim',
'AdaBoost_7_Iletisim',
'NeuralNetwork_7_Iletisim',
'SVM_7_Iletisim',
'KNN_7_Iletisim',
'RandomForest_7_Iletisim',
'XGBoost_7_Iletisim',
'LightGBM_7_Iletisim',
'DecisionTree_7_Iletisim',
'KNN_13_Otizm',
'AdaBoost_12_Otizm',
'NeuralNetwork_8_Otizm',
'LightGBM_8_Otizm',
'AdaBoost_8_Otizm',
'AdaBoost_13_Otizm',
'RandomForest_8_Otizm',
'LogisticRegression_12_Otizm',
'XGBoost_8_Otizm',
'SVM_12_Otizm',
'LogisticRegression_8_Otizm',
'LightGBM_13_Otizm',
'KNN_12_Otizm',
'KNN_8_Otizm',
'NeuralNetwork_13_Otizm',
'LightGBM_7_DEHB',
'NeuralNetwork_7_DEHB',
'DecisionTree_7_DEHB',
'XGBoost_7_DEHB',
'SVM_7_DEHB',
'RandomForest_7_DEHB',
'KNN_7_DEHB',
'NeuralNetwork_20_Dil ve Konuşma Bozuklukları',
'KNN_20_Dil ve Konuşma Bozuklukları',
'DecisionTree_8_Dil ve Konuşma Bozuklukları',
'XGBoost_20_Dil ve Konuşma Bozuklukları',
'DecisionTree_20_Dil ve Konuşma Bozuklukları',
'AdaBoost_13_Gelişimsel Koordinasyon Bozukluğu',
'XGBoost_13_Gelişimsel Koordinasyon Bozukluğu',
'LightGBM_13_Gelişimsel Koordinasyon Bozukluğu',
'RandomForest_13_Gelişimsel Koordinasyon Bozukluğu',
'KNN_13_Gelişimsel Koordinasyon Bozukluğu',
'SVM_13_Gelişimsel Koordinasyon Bozukluğu',
'NeuralNetwork_13_Gelişimsel Koordinasyon Bozukluğu',
'LogisticRegression_13_Gelişimsel Koordinasyon Bozukluğu',
'DecisionTree_13_Gelişimsel Koordinasyon Bozukluğu',
'KNN_20_Zihinsel Yetersizlik',
'RandomForest_7_Zihinsel Yetersizlik',
'XGBoost_7_Zihinsel Yetersizlik',
'DecisionTree_7_Zihinsel Yetersizlik',
'AdaBoost_20_Zihinsel Yetersizlik',
'LightGBM_7_Zihinsel Yetersizlik',
'SVM_7_Zihinsel Yetersizlik',
'DecisionTree_6_Zihinsel Yetersizlik',
'LightGBM_6_Zihinsel Yetersizlik',
'XGBoost_6_Zihinsel Yetersizlik',
'RandomForest_6_Zihinsel Yetersizlik',
'NeuralNetwork_7_Zihinsel Yetersizlik',
'KNN_7_Zihinsel Yetersizlik'
]

# Dosya yolları
MODEL_DIR = 'models'  # Model dosyalarının bulunduğu klasör
FEATURE_FILE = "selected_features.xlsx"
PERFORMANCE_FILE = "model_performance.xlsx" 